
all:train-car.c
	gcc train-car.c -o try.o
clean:
	rm try.o
run:
	./try.o

all1:part1.c
	gcc part1.c -o try.o

all2:part2.c
	gcc part2.c -o try.o

all2B:part2B.c
	gcc part2B.c -o try.o

all3:part3.c
	gcc part3.c -o try.o

all3B:part3B.c
	gcc part3B.c -o try.o